[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
optimizer = true
optimizerRuns = 20_00
extra_output = ["storageLayout"]
build_info = true
viaIR = true
ast = true
ffi = true
fs_permissions = [ {access = "read-write",  path ="./"}]
remappings = [
    "@forge-std = home/phydy/Work/Personal/forge-std/src",
]

[rpc_endpoints]
localhost = "http://localhost:8545"
sepolia = "${ALCHEMY_RPC_URL}"
hedera = "${HEDERA_RPC_URL}"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options